accepted = [
    "EUPL-1.2",
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "Unicode-3.0",
    "CC0-1.0",
]
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
ignore-build-dependencies = false
ignore-dev-dependencies = false
ignore-transitive-dependencies = false
workarounds = ["unicode-ident", "chrono"]
