[workspace]
members = ["xtask"]

[package]
name = "verdi"
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"
authors = ["Matilde Morrone <contact@morrone.dev>"]
readme = "README.md"
repository = "https://github.com/verdiwm/verdi"
publish = false

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
anyhow = "1.0.97"
bytes = "1.10.1"
rustix = { version = "1.0.1", features = ["fs", "mm", "process"] }
thiserror = "2.0.12"
tokio = { version = "1.43.0", features = [
    "macros",
    "net",
    "rt-multi-thread",
    "signal",
    "sync",
    "tracing",
    "process",
] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
    "env-filter",
    "tracing-log",
] }
wgpu = { version = "24.0.0", default-features = false, features = [
    "vulkan",
    "wgsl",
] }
clap = { version = "4.5.31", features = ["derive"] }
serde = { version = "1.0.218", features = ["derive"] }
diretto = "0.0.7"
raw-window-handle = "0.6.2"
rand = "0.9.0"
bytemuck = { version = "1.21.0", features = ["derive"] }
colpetto = { version = "0.6.0", features = ["tokio", "tracing"] }
waynest = { version = "0.0.25", features = ["server", "stable"] }
home = "0.5.11"
tokio-stream = { version = "0.1.17", features = ["sync"] }
libcorn = "0.10.0"

[build-dependencies]
chrono = { version = "0.4.39", default-features = false, features = ["std"] }
git2 = { version = "0.20.0", default-features = false }

[patch.crates-io]
wgpu = { git = "https://github.com/gfx-rs/wgpu" }
libcorn = { git = "https://github.com/corn-config/corn" }
# diretto = { git = "https://github.com/verdiwm/diretto.git" }
# colpetto = { path = "../colpetto" }
# waynest = { path = "../waynest" }
