[workspace]
members = ["xtask"]

[package]
name = "verdi"
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"
authors = ["Federico Maria Morrone <contact@morrone.dev>"]
readme = "README.md"
repository = "https://github.com/verdiwm/verdi"
publish = false

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
anyhow = "1.0.95"
bytes = "1.9.0"
rustix = { version = "0.38.43", features = ["fs", "mm", "process"] }
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = [
    "macros",
    "net",
    "rt-multi-thread",
    "signal",
    "sync",
    "tracing",
] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
    "env-filter",
    "tracing-log",
] }
wgpu = { version = "24.0.0", default-features = false, features = ["wgsl"] }
clap = { version = "4.5.26", features = ["derive"] }
toml_edit = { version = "0.22.22", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
diretto = "0.0.5"
raw-window-handle = "0.6.2"
rand = "0.9.0"
bytemuck = { version = "1.21.0", features = ["derive"] }
colpetto = { version = "0.4.0", features = ["tokio", "tracing"] }
waynest = { version = "0.0.21", features = ["server", "stable"] }
home = "0.5.11"
tokio-stream = { version = "0.1.17", features = ["sync"] }

[build-dependencies]
chrono = { version = "0.4.39", default-features = false, features = ["std"] }
git2 = { version = "0.20.0", default-features = false }

[patch.crates-io]
wgpu = { git = "https://github.com/verdiwm/wgpu", branch = "drm-support" }
raw-window-handle = { git = "https://github.com/morr0ne/raw-window-handle", branch = "drm-connector" }
# diretto = { git = "https://github.com/verdiwm/diretto.git" }
# colpetto = { path = "../colpetto" }
# waynest = { path = "../waynest" }
