[graph]
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]

[advisories]
ignore = [
    "RUSTSEC-2024-0436", # FIXME: this is the paste crate deprecation but it requires fixing on waynest side
]

[licenses]
confidence-threshold = 0.93
allow = [
    "EUPL-1.2",
    "Apache-2.0",
    "MIT",
    "ISC",
    "Zlib",
    "Unicode-3.0",
    "CC0-1.0",
]

[sources]
allow-git = [
    "https://github.com/corn-config/corn",
    "https://github.com/tokio-rs/tracing",
]

[sources.allow-org]
github = ["verdiwm"]
