name: ci
on: [push, pull_request]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/verdiwm/ci-image:latest
    steps:
      - uses: actions/checkout@v4

      - name: Try building
        run: cargo xtask build

  lint:
    name: Lint project
    runs-on: ubuntu-latest
    container: ghcr.io/verdiwm/ci-image:latest
    steps:
      - uses: actions/checkout@v4

      - name: Check clippy
        run: cargo clippy --all-targets --all-features

  fmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    container: ghcr.io/verdiwm/ci-image:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run formatter
        run: cargo fmt --check

  deny:
    name: Run cargo-deny
    runs-on: ubuntu-latest
    container: ghcr.io/verdiwm/ci-image:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v2
